/*
	Copyright 2020 Mohamed Shalan

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at:

	http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/

`timescale          1ns/1ps
`default_nettype    none

/*
    DMA Controller

    Register map (generated by regblock -- see MS_DMAC_AHBL_regs.yml):
    0x00: CTRL   -- en[0], trigger[11:8], src_type[17:16], src_ai[20:18],
                    dest_type[25:24], dest_ai[28:26]
    0x04: STATUS -- done[0] (read-only)
    0x08: SADDR  -- source base address
    0x0C: DADDR  -- destination base address
    0x10: SIZE   -- frame size (number of transfers minus one) [15:0]
    0x14: TRIG   -- write 1 to software-trigger a transfer (self-clearing)
    0x18: FC     -- frame count [7:0] (decremented by HW each completed frame)
*/

module MS_DMAC_AHBL (
    input   wire    HCLK,
    input   wire    HRESETn,

    output  wire    IRQ,

    // AHB-Lite Slave Interface

    input wire          HSEL,
    input wire [31:0]   HADDR,
    input wire [1:0]    HTRANS,
    input wire          HWRITE,
    input wire          HREADY,
    input wire [31:0]   HWDATA,
    input wire [2:0]    HSIZE,
    output wire         HREADYOUT,
    output wire [31:0]  HRDATA,

    // AHB-Lite Master Interface

    output wire [31:0]  M_HADDR,
    output wire [1:0]   M_HTRANS,
    output wire [2:0]   M_HSIZE,
    output wire         M_HWRITE,
    output wire [31:0]  M_HWDATA,
    input wire          M_HREADY,
    input wire [31:0]   M_HRDATA,

    // Peripherals IRQ lines
    input wire          PIRQ
);

    //
    // Register block
    //

    // Gate htrans with HSEL -- regblock has no HSEL port
    wire [1:0] ahbls_htrans = HTRANS & {2{HSEL}};

    wire        ctrl_en_o;
    wire [3:0]  ctrl_trigger_o;
    wire [1:0]  ctrl_src_type_o;
    wire [2:0]  ctrl_src_ai_o;
    wire [1:0]  ctrl_dest_type_o;
    wire [2:0]  ctrl_dest_ai_o;
    wire        trig_val_o;
    wire [7:0]  fc_val_o;
    wire        fc_val_wen;
    wire [31:0] saddr_val_o;
    wire [31:0] daddr_val_o;
    wire [15:0] size_val_o;
    wire [7:0]  fc_val_i;
    wire        icr_done_o;

    MS_DMAC_AHBL_regs regs (
        .clk              (HCLK),
        .rst_n            (HRESETn),
        .ahbls_haddr      (HADDR[15:0]),
        .ahbls_htrans     (ahbls_htrans),
        .ahbls_hwrite     (HWRITE),
        .ahbls_hsize      (HSIZE),
        .ahbls_hready     (HREADY),
        .ahbls_hwdata     (HWDATA),
        .ahbls_hready_resp(HREADYOUT),
        .ahbls_hrdata     (HRDATA),
        .ahbls_hresp      (),
        .ctrl_en_o        (ctrl_en_o),
        .ctrl_trigger_o   (ctrl_trigger_o),
        .ctrl_src_type_o  (ctrl_src_type_o),
        .ctrl_src_ai_o    (ctrl_src_ai_o),
        .ctrl_dest_type_o (ctrl_dest_type_o),
        .ctrl_dest_ai_o   (ctrl_dest_ai_o),
        .status_done_i    (done),
        .saddr_val_o      (saddr_val_o),
        .daddr_val_o      (daddr_val_o),
        .size_val_o       (size_val_o),
        .trig_val_o       (trig_val_o),
        .fc_val_i         (fc_val_i),
        .fc_val_o         (fc_val_o),
        .fc_val_wen       (fc_val_wen),
        .icr_done_i       (irq_pulse),
        .icr_done_o       (icr_done_o)
    );

    // FC register storage -- rwv means regblock passes writes through;
    // the top module owns the register and handles the HW decrement.
    reg [7:0] fc_reg;
    always @(posedge HCLK or negedge HRESETn) begin
        if (!HRESETn)
            fc_reg <= 8'h0;
        else if (fc_val_wen)
            fc_reg <= fc_val_o;
        else if (done && (state == WD_STATE))
            fc_reg <= fc_reg - 1'b1;
    end
    assign fc_val_i = fc_reg;

    //
    // IRQ
    //

    wire done;
    // irq_pulse: fires on every completed transfer regardless of trigger mode or FC count
    wire irq_pulse = done;
    // IRQ is driven from the latched ICR bit so it stays asserted until SW clears it
    assign IRQ = icr_done_o;

    //
    // AHB Master Logic
    //

    wire trigger = (trig_val_o && (ctrl_trigger_o == 4'b0)) ||
                   (|({3'b0, PIRQ} & ctrl_trigger_o));

    // DMA FSM
    localparam  IDLE_STATE  = 5'b00001,
                RA_STATE    = 5'b00010,
                RD_STATE    = 5'b00100,
                WA_STATE    = 5'b01000,
                WD_STATE    = 5'b10000;

    reg [4:0] state, nstate;

    always @(posedge HCLK or negedge HRESETn)
        if (!HRESETn) state <= IDLE_STATE;
        else state <= nstate;

    always @*
        case (state)
            IDLE_STATE: if (trigger & ctrl_en_o)
                            nstate = RA_STATE;
                        else
                            nstate = IDLE_STATE;
            RA_STATE:   if (M_HREADY) nstate = RD_STATE; else nstate = RA_STATE;
            RD_STATE:   if (M_HREADY) nstate = WA_STATE; else nstate = RD_STATE;
            WA_STATE:   if (M_HREADY) nstate = WD_STATE; else nstate = WA_STATE;
            WD_STATE:   if (M_HREADY) begin
                            if (done)
                                nstate = IDLE_STATE;
                            else
                                nstate = RA_STATE;
                        end else nstate = WD_STATE;
            default: nstate = state;
        endcase

    // Address sequence generator
    reg  [15:0] CNTR;
    wire [17:0] R_CNTR = (ctrl_src_ai_o == 4) ? {2'b0, CNTR} << 2 :
                         (ctrl_src_ai_o == 2) ? {2'b0, CNTR} << 1 :
                         (ctrl_src_ai_o == 1) ? {2'b0, CNTR}      : {2'b0, CNTR};
    wire [17:0] W_CNTR = (ctrl_dest_ai_o == 4) ? {2'b0, CNTR} << 2 :
                         (ctrl_dest_ai_o == 2) ? {2'b0, CNTR} << 1 :
                         (ctrl_dest_ai_o == 1) ? {2'b0, CNTR}      : {2'b0, CNTR};
    wire [31:0] R_ADDR = (ctrl_src_ai_o  != 0) ? (saddr_val_o + 32'(R_CNTR)) : saddr_val_o;
    wire [31:0] W_ADDR = (ctrl_dest_ai_o != 0) ? (daddr_val_o + 32'(W_CNTR)) : daddr_val_o;

    always @(posedge HCLK or negedge HRESETn)
        if (!HRESETn)
            CNTR <= 16'h0;
        else if (trig_val_o)
            CNTR <= 16'h0;
        else if (done && (state == WD_STATE))
            CNTR <= 16'h0;
        else if ((state == WD_STATE) & M_HREADY & ((ctrl_src_ai_o != 0) || (ctrl_dest_ai_o != 0)))
            CNTR <= CNTR + 16'h1;

    assign done = (CNTR == size_val_o) & ctrl_en_o;

    // Master port
    reg [31:0] rdata;

    always @(posedge HCLK)
        if ((state == RD_STATE) & M_HREADY)
            rdata <= M_HRDATA;

    // case: moving first half-words from 2-word source into 1-word destination
    wire [31:0] aligned_rdata = (ctrl_src_type_o == 2 & ctrl_dest_type_o == 1 & M_HADDR[1]) ?
                                 {rdata[15:0], rdata[15:0]} : rdata;

    assign M_HADDR   = (state == RA_STATE) ? R_ADDR : W_ADDR;
    assign M_HTRANS  = M_HREADY & ((state == RA_STATE) || (state == WA_STATE)) ? 2'h2 : 2'h0;
    assign M_HWDATA  = (state == WD_STATE) ? aligned_rdata : 32'hEEEEEEEE;
    assign M_HWRITE  = (state == WA_STATE) ? 1'b1 : 1'b0;
    assign M_HSIZE   = (state == RA_STATE) ? {1'b0, ctrl_src_type_o} : {1'b0, ctrl_dest_type_o};

endmodule
