/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _MS_DMAC_AHBL_REGS_H_
#define _MS_DMAC_AHBL_REGS_H_

// Block name           : MS_DMAC_AHBL
// Bus type             : ahbl
// Bus data width       : 32
// Bus address width    : 16

// AHB-Lite DMA Controller registers

#define MS_DMAC_AHBL_CTRL_OFFS 0
#define MS_DMAC_AHBL_STATUS_OFFS 4
#define MS_DMAC_AHBL_SADDR_OFFS 8
#define MS_DMAC_AHBL_DADDR_OFFS 12
#define MS_DMAC_AHBL_SIZE_OFFS 16
#define MS_DMAC_AHBL_TRIG_OFFS 20
#define MS_DMAC_AHBL_FC_OFFS 24
#define MS_DMAC_AHBL_ICR_OFFS 28

#ifndef __ASSEMBLER__
#include <stdint.h>

typedef struct {
	volatile uint32_t ctrl;
	volatile uint32_t status;
	volatile uint32_t saddr;
	volatile uint32_t daddr;
	volatile uint32_t size;
	volatile uint32_t trig;
	volatile uint32_t fc;
	volatile uint32_t icr;
} MS_DMAC_AHBL_hw_t;

#endif // !__ASSEMBLER__


/*******************************************************************************
*                                     CTRL                                     *
*******************************************************************************/

// Control register

// Field: CTRL_EN  Access: RW
// Reset: 0x0
// DMA enable
#define MS_DMAC_AHBL_CTRL_EN_LSB  0
#define MS_DMAC_AHBL_CTRL_EN_BITS 1
#define MS_DMAC_AHBL_CTRL_EN_MASK 0x1
// Field: CTRL_TRIGGER  Access: RW
// Reset: 0x0
// Transfer trigger source - 0=software
#define MS_DMAC_AHBL_CTRL_TRIGGER_LSB  8
#define MS_DMAC_AHBL_CTRL_TRIGGER_BITS 4
#define MS_DMAC_AHBL_CTRL_TRIGGER_MASK 0xf00
// Field: CTRL_SRC_TYPE  Access: RW
// Reset: 0x0
// Source data type - 0=byte 1=halfword 2=word
#define MS_DMAC_AHBL_CTRL_SRC_TYPE_LSB  16
#define MS_DMAC_AHBL_CTRL_SRC_TYPE_BITS 2
#define MS_DMAC_AHBL_CTRL_SRC_TYPE_MASK 0x30000
// Field: CTRL_SRC_AI  Access: RW
// Reset: 0x0
// Source address auto-increment mode
#define MS_DMAC_AHBL_CTRL_SRC_AI_LSB  18
#define MS_DMAC_AHBL_CTRL_SRC_AI_BITS 3
#define MS_DMAC_AHBL_CTRL_SRC_AI_MASK 0x1c0000
// Field: CTRL_DEST_TYPE  Access: RW
// Reset: 0x0
// Destination data type - 0=byte 1=halfword 2=word
#define MS_DMAC_AHBL_CTRL_DEST_TYPE_LSB  24
#define MS_DMAC_AHBL_CTRL_DEST_TYPE_BITS 2
#define MS_DMAC_AHBL_CTRL_DEST_TYPE_MASK 0x3000000
// Field: CTRL_DEST_AI  Access: RW
// Reset: 0x0
// Destination address auto-increment mode
#define MS_DMAC_AHBL_CTRL_DEST_AI_LSB  26
#define MS_DMAC_AHBL_CTRL_DEST_AI_BITS 3
#define MS_DMAC_AHBL_CTRL_DEST_AI_MASK 0x1c000000

/*******************************************************************************
*                                    STATUS                                    *
*******************************************************************************/

// Status register

// Field: STATUS_DONE  Access: ROV
// Reset: 0x0
// Transfer complete flag
#define MS_DMAC_AHBL_STATUS_DONE_LSB  0
#define MS_DMAC_AHBL_STATUS_DONE_BITS 1
#define MS_DMAC_AHBL_STATUS_DONE_MASK 0x1

/*******************************************************************************
*                                    SADDR                                     *
*******************************************************************************/

// Source address register

// Field: SADDR_VAL  Access: RW
// Reset: 0x0
// Source base address
#define MS_DMAC_AHBL_SADDR_VAL_LSB  0
#define MS_DMAC_AHBL_SADDR_VAL_BITS 32
#define MS_DMAC_AHBL_SADDR_VAL_MASK 0xffffffff

/*******************************************************************************
*                                    DADDR                                     *
*******************************************************************************/

// Destination address register

// Field: DADDR_VAL  Access: RW
// Reset: 0x0
// Destination base address
#define MS_DMAC_AHBL_DADDR_VAL_LSB  0
#define MS_DMAC_AHBL_DADDR_VAL_BITS 32
#define MS_DMAC_AHBL_DADDR_VAL_MASK 0xffffffff

/*******************************************************************************
*                                     SIZE                                     *
*******************************************************************************/

// Frame size register

// Field: SIZE_VAL  Access: RW
// Reset: 0x0
// Number of transfers minus one
#define MS_DMAC_AHBL_SIZE_VAL_LSB  0
#define MS_DMAC_AHBL_SIZE_VAL_BITS 16
#define MS_DMAC_AHBL_SIZE_VAL_MASK 0xffff

/*******************************************************************************
*                                     TRIG                                     *
*******************************************************************************/

// Software trigger register

// Field: TRIG_VAL  Access: SC
// Reset: 0x0
// Write 1 to initiate a software-triggered DMA transfer
#define MS_DMAC_AHBL_TRIG_VAL_LSB  0
#define MS_DMAC_AHBL_TRIG_VAL_BITS 1
#define MS_DMAC_AHBL_TRIG_VAL_MASK 0x1

/*******************************************************************************
*                                      FC                                      *
*******************************************************************************/

// Frame count register

// Field: FC_VAL  Access: RWV
// Reset: 0x0
// Remaining frame count decremented by hardware on each completed frame
#define MS_DMAC_AHBL_FC_VAL_LSB  0
#define MS_DMAC_AHBL_FC_VAL_BITS 8
#define MS_DMAC_AHBL_FC_VAL_MASK 0xff

/*******************************************************************************
*                                     ICR                                      *
*******************************************************************************/

// Interrupt clear register

// Field: ICR_DONE  Access: W1C
// Reset: 0x0
// Latched transfer-complete interrupt status - set by hardware on done pulse -
// write 1 to clear
#define MS_DMAC_AHBL_ICR_DONE_LSB  0
#define MS_DMAC_AHBL_ICR_DONE_BITS 1
#define MS_DMAC_AHBL_ICR_DONE_MASK 0x1

#endif // _MS_DMAC_AHBL_REGS_H_
