/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : MS_DMAC_AHBL
// Bus type             : ahbl
// Bus data width       : 32
// Bus address width    : 16

// AHB-Lite DMA Controller registers

module MS_DMAC_AHBL_regs (
	input wire         clk,
	input wire         rst_n,
	
	// AHB-Lite Port
	input  wire [15:0] ahbls_haddr,
	input  wire [1:0]  ahbls_htrans,
	input  wire        ahbls_hwrite,
	input  wire [2:0]  ahbls_hsize,
	input  wire        ahbls_hready,
	output wire        ahbls_hready_resp,
	input  wire [31:0] ahbls_hwdata,
	output wire [31:0] ahbls_hrdata,
	output wire        ahbls_hresp,
	
	// Register interfaces
	output reg         ctrl_en_o,
	output reg  [3:0]  ctrl_trigger_o,
	output reg  [1:0]  ctrl_src_type_o,
	output reg  [2:0]  ctrl_src_ai_o,
	output reg  [1:0]  ctrl_dest_type_o,
	output reg  [2:0]  ctrl_dest_ai_o,
	input  wire        status_done_i,
	output reg  [31:0] saddr_val_o,
	output reg  [31:0] daddr_val_o,
	output reg  [15:0] size_val_o,
	output reg         trig_val_o,
	input  wire [7:0]  fc_val_i,
	output reg  [7:0]  fc_val_o,
	output reg         fc_val_wen,
	input  wire        icr_done_i,
	output reg         icr_done_o
);

/* verilator lint_off UNUSEDSIGNAL */
// AHB-Lite adapter
wire [31:0] wdata = ahbls_hwdata;
reg         wen;
reg         ren;
reg  [15:0] addr;
always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		wen <= 1'b0;
		ren <= 1'b0;
		addr <= 16'd0;
	end else if (ahbls_hready) begin
		wen <= ahbls_htrans[1] && ahbls_hwrite;
		ren <= ahbls_htrans[1] && !ahbls_hwrite;
		addr <= ahbls_haddr & 16'h1c;
	end
end

reg  [31:0] rdata;
assign ahbls_hrdata = rdata;
assign ahbls_hready_resp = 1'b1;
assign ahbls_hresp = 1'b0;

localparam ADDR_CTRL = 0;
localparam ADDR_STATUS = 4;
localparam ADDR_SADDR = 8;
localparam ADDR_DADDR = 12;
localparam ADDR_SIZE = 16;
localparam ADDR_TRIG = 20;
localparam ADDR_FC = 24;
localparam ADDR_ICR = 28;

wire __ctrl_wen = wen && addr == ADDR_CTRL;
wire __ctrl_ren = ren && addr == ADDR_CTRL;
wire __status_wen = wen && addr == ADDR_STATUS;
wire __status_ren = ren && addr == ADDR_STATUS;
wire __saddr_wen = wen && addr == ADDR_SADDR;
wire __saddr_ren = ren && addr == ADDR_SADDR;
wire __daddr_wen = wen && addr == ADDR_DADDR;
wire __daddr_ren = ren && addr == ADDR_DADDR;
wire __size_wen = wen && addr == ADDR_SIZE;
wire __size_ren = ren && addr == ADDR_SIZE;
wire __trig_wen = wen && addr == ADDR_TRIG;
wire __trig_ren = ren && addr == ADDR_TRIG;
wire __fc_wen = wen && addr == ADDR_FC;
wire __fc_ren = ren && addr == ADDR_FC;
wire __icr_wen = wen && addr == ADDR_ICR;
wire __icr_ren = ren && addr == ADDR_ICR;

wire        ctrl_en_wdata = wdata[0];
wire        ctrl_en_rdata;
wire [3:0]  ctrl_trigger_wdata = wdata[11:8];
wire [3:0]  ctrl_trigger_rdata;
wire [1:0]  ctrl_src_type_wdata = wdata[17:16];
wire [1:0]  ctrl_src_type_rdata;
wire [2:0]  ctrl_src_ai_wdata = wdata[20:18];
wire [2:0]  ctrl_src_ai_rdata;
wire [1:0]  ctrl_dest_type_wdata = wdata[25:24];
wire [1:0]  ctrl_dest_type_rdata;
wire [2:0]  ctrl_dest_ai_wdata = wdata[28:26];
wire [2:0]  ctrl_dest_ai_rdata;
wire [31:0] __ctrl_rdata = {3'h0, ctrl_dest_ai_rdata, ctrl_dest_type_rdata, 3'h0, ctrl_src_ai_rdata, ctrl_src_type_rdata, 4'h0, ctrl_trigger_rdata, 7'h0, ctrl_en_rdata};
assign ctrl_en_rdata = ctrl_en_o;
assign ctrl_trigger_rdata = ctrl_trigger_o;
assign ctrl_src_type_rdata = ctrl_src_type_o;
assign ctrl_src_ai_rdata = ctrl_src_ai_o;
assign ctrl_dest_type_rdata = ctrl_dest_type_o;
assign ctrl_dest_ai_rdata = ctrl_dest_ai_o;

wire        status_done_wdata = wdata[0];
wire        status_done_rdata;
wire [31:0] __status_rdata = {31'h0, status_done_rdata};
assign status_done_rdata = status_done_i;

wire [31:0] saddr_val_wdata = wdata[31:0];
wire [31:0] saddr_val_rdata;
wire [31:0] __saddr_rdata = {saddr_val_rdata};
assign saddr_val_rdata = saddr_val_o;

wire [31:0] daddr_val_wdata = wdata[31:0];
wire [31:0] daddr_val_rdata;
wire [31:0] __daddr_rdata = {daddr_val_rdata};
assign daddr_val_rdata = daddr_val_o;

wire [15:0] size_val_wdata = wdata[15:0];
wire [15:0] size_val_rdata;
wire [31:0] __size_rdata = {16'h0, size_val_rdata};
assign size_val_rdata = size_val_o;

wire        trig_val_wdata = wdata[0];
wire        trig_val_rdata;
wire [31:0] __trig_rdata = {31'h0, trig_val_rdata};
assign trig_val_rdata = 1'h0;

wire [7:0]  fc_val_wdata = wdata[7:0];
wire [7:0]  fc_val_rdata;
wire [31:0] __fc_rdata = {24'h0, fc_val_rdata};
assign fc_val_rdata = fc_val_i;

wire        icr_done_wdata = wdata[0];
wire        icr_done_rdata;
wire [31:0] __icr_rdata = {31'h0, icr_done_rdata};
reg        icr_done;
assign icr_done_rdata = icr_done;
/* verilator lint_on UNUSEDSIGNAL */

always @ (*) begin
	case (addr)
		ADDR_CTRL: rdata = __ctrl_rdata;
		ADDR_STATUS: rdata = __status_rdata;
		ADDR_SADDR: rdata = __saddr_rdata;
		ADDR_DADDR: rdata = __daddr_rdata;
		ADDR_SIZE: rdata = __size_rdata;
		ADDR_TRIG: rdata = __trig_rdata;
		ADDR_FC: rdata = __fc_rdata;
		ADDR_ICR: rdata = __icr_rdata;
		default: rdata = 32'h0;
	endcase
	trig_val_o = trig_val_wdata & {1{__trig_wen}};
	fc_val_wen = __fc_wen;
	fc_val_o = fc_val_wdata;
	icr_done_o = icr_done;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		ctrl_en_o <= 1'h0;
		ctrl_trigger_o <= 4'h0;
		ctrl_src_type_o <= 2'h0;
		ctrl_src_ai_o <= 3'h0;
		ctrl_dest_type_o <= 2'h0;
		ctrl_dest_ai_o <= 3'h0;
		saddr_val_o <= 32'h0;
		daddr_val_o <= 32'h0;
		size_val_o <= 16'h0;
		icr_done <= 1'h0;
	end else begin
		if (__ctrl_wen)
			ctrl_en_o <= ctrl_en_wdata;
		if (__ctrl_wen)
			ctrl_trigger_o <= ctrl_trigger_wdata;
		if (__ctrl_wen)
			ctrl_src_type_o <= ctrl_src_type_wdata;
		if (__ctrl_wen)
			ctrl_src_ai_o <= ctrl_src_ai_wdata;
		if (__ctrl_wen)
			ctrl_dest_type_o <= ctrl_dest_type_wdata;
		if (__ctrl_wen)
			ctrl_dest_ai_o <= ctrl_dest_ai_wdata;
		if (__saddr_wen)
			saddr_val_o <= saddr_val_wdata;
		if (__daddr_wen)
			daddr_val_o <= daddr_val_wdata;
		if (__size_wen)
			size_val_o <= size_val_wdata;
		icr_done <= (icr_done & ~({1{__icr_wen}} & icr_done_wdata)) | icr_done_i;
	end
end

endmodule
